version: "3.7"

networks:
  kong-net:
    name: kong-net
    driver: bridge
   
# cat .env
#CONVERT_PORT=8081

services:
  convert-api:
    build:
      context: ./ms/convert
      dockerfile: ./Dockerfile
    image: convert/api
    environment:
      - CONVERT_PROFILE=dev
      - SERVER_PORT=${CONVERT_PORT}
    ports:
      - "${CONVERT_PORT}:${CONVERT_PORT}"
    networks:
      - kong-net